### ISSUE TITLE
main.CRITICAL: exception 'ReflectionException' with message 'Method estimateRatesByAddressId does not exist' in D:\wamp\www\singapore-mint\magento\vendor\zendframework\zend-code\src\Reflection\ClassReflection.php:158

### ISSUE THREAD

**Issue by shahankitb997** [shopgo-magento2/checkout-city#1]
On Magento 2.1.3 it gives

main.CRITICAL: exception 'ReflectionException' with message 'Method estimateRatesByAddressId does not exist' in D:\wamp\www\singapore-mint\magento\vendor\zendframework\zend-code\src\Reflection\ClassReflection.php:158

**Comment by kwakukuffour** [comment]
Am experiencing the same error estimateRatesByAddressId does not exist, how did you resolve it?
